About us and Advantages
ratifire/devrate-ratifire pull request #3
Opened 2024-10-11 17:53 UTC by BlackPuma9

2024-10-11 18:21 UTC, VladimirShaitan requested changes
Перевір моменти з ID вони мені не подобаються
також подивись і додай семантичних тегів 
Класи в тебе не по БЕМу але вже хай так і буде

2024-10-11 18:21 UTC, VladimirShaitan commented on src/pages/components/about_us.html
>  <section id="about_us">
Якщо не використовуєш якорні посилання то не треба id

2024-10-11 18:21 UTC, VladimirShaitan commented on src/pages/components/about_us.html
> +      <div class="about_us-img"></div>
напервне тут повинен бути тег img

2024-10-11 18:21 UTC, VladimirShaitan commented on src/pages/components/advantages.html
>  <section id="advantages">
id може не треба

2024-10-11 18:21 UTC, VladimirShaitan commented on src/pages/components/advantages.html
> +      <div class="advantages-img"></div>
Картинка ?

2024-10-11 18:21 UTC, VladimirShaitan commented on src/scss/common/mixins.scss
> +  margin-bottom: 16px;
Всі властивості котрі не приймають в якості значень змінні винести в екстенд
https://sass-lang.com/guide/#extend-inheritance

2024-10-11 18:21 UTC, VladimirShaitan commented on src/scss/components/advantages/advantages.scss
> +  height: 640px;
Не треба задавати статичну висоту та ширину картинкам

2024-10-12 18:56 UTC, BlackPuma9 commented on src/pages/components/advantages.html
>  <section id="advantages">
видаляю

2024-10-12 19:03 UTC, BlackPuma9 commented on src/pages/components/advantages.html
> +      <div class="advantages-img"></div>
replaced with picture

2024-10-12 19:07 UTC, BlackPuma9 commented on src/pages/components/about_us.html
> +      <div class="about_us-img"></div>
замінила на картинки

2024-10-12 21:09 UTC, BlackPuma9 commented on src/pages/components/about_us.html
>  <section id="about_us">
поняла. Якорні посилання викорисала в about us, contacts & team section. Все решта видалила

2024-10-12 23:27 UTC, BlackPuma9 commented on src/scss/common/mixins.scss
> +  margin-bottom: 16px;
зробила, дякую!

2024-10-13 21:39 UTC, merged